version: '3.8'

services:
  react-app:
    container_name: frontend
    build: .
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - .:/app
      - /app/node_modules
